---
title: "학습관점에서 비교하는 dplyr과 data.table"
categories: [data.table, R]
---

R로 데이터 핸들링을 할 때, `dplyr`와 `data.table`을 많이 활용합니다. 저 역시 두 가지를 모두 사용하고 있습니다.

이 두 가지를 사용하면서 dplyr보다 data.table을 추천드리는지 학습과정 차원에서 말씀드리겠습니다.

1.  간단함

    dplyr보다 data.table의 코드가 더 간단합니다. 간단하다는 것은 입력하는 코드가 적은 것은 물론, 숙지해야 할 문법 (또는 함수)도 더 단순합니다.

    dplyr는 원하는 기능을 함수이름으로 설정해 놓았습니다. 그렇기 때문에 함수 자체를 익히는 것은 크게 어렵지 않습니다. 문제는 외워야 할 함수가 너무 많다는 것입니다.

    `select()`, `mutate()`, `filter()`, `summarise()`, `filter()`, `recode()`, `case_when()` 등등..

    또한 여러 가지 변수를 동시에 다루는 작업이라면 더욱 복잡해집니다. `~` 가 붙는 코드, `.`이 붙는 코드들이 생겨나면서 처음 배우는 사람들에게는 코드를 이해하는 데 어려움이 생깁니다.

    반면 `data.table` 안에서 기본적인 동작들은 함수가 아닌 문법을 통해 해결할 수 있습니다. `[]`가 들어간 문법을 처음또한 사용하는 함수의 종류도 크게 많지 않아 훨씬

2.  패키지 의존성

    `dplyr`는 tidyverse라는 생태계에 속한 패키지입니다. 추가적인 동작을 사용하기 위해선 tidyr, broom 등과 같은 패키지를 설치해야만 합니다. 어느 패키지에 어떤 함수가 있는지 알아야 하고, 필요한 패키지를 추가적으로 설치해야 합니다. 그 패키지들도 설치하려면 다른 패키지가 필요해서 필요한 패키지 이외에도 여러 패키지들을 다운로드받아야 합니다.

    반면에 data.table은 data.table 패키지 하나만 설치하면 끝이죠.

------------------------------------------------------------------------

"일본어는 처음엔 쉬운데, 나중엔 갈수록 어려워져. 반대로 중국어는 처음엔 어려운데, 나중엔 쉬워져"

중국어를 배울 때 자주 들었던 말입니다. 어문계열 출신이다보니 중국어를 배울 때 항상 일본어와 비교를 하는 말을 들었습니다. 일본어는 어순도 우리나라와 비슷하고, 애니메이션 등의 영향으로 많이 익숙하죠. 반면에 중국어는 어순도 한국어와 다르고, 무엇보다 성조도 있죠. 그래서 중국어에 대한 진입장벽이 일본어보다 더 높다고들 얘기했던 기억이 납니다.

저는 dplyr와 data.table의 관계가 일본어와 중국어와 비슷하다고 생각합니다.

dplyr는 처음엔 쉽습니다. 함수 몇 개만 알면 기본적인 분석은 다 해낼 수 있습니다. 파이프 연산자를 이용해 코드를 읽어나가는 것도 더 쉽게 느낄 수 있습니다. 하지만 추가적인 작업을 하기 위해서는 여러 함수를 더 익혀야 합니다. 알아둬야하는 함수가 많아지고, 새로운 문법도 늘어납니다.

반면에 `data.table`은 처음에 문법을 익히기가 어렵습니다. i, j, by 가 뭔지 이해해야 하는 것이 익숙하지 않습니다. 하지만 이 문법을 잘 이해하고 나면 다음부터는 외워야 할 함수가 거의 없습니다.

`dplyr`를 왜 더 많이 쓸까?

`dplyr`가 있는 `tidyverse`를 밀어주는 느낌이 없잖아 있습니다. Posit을 보면 `tidyverse`와 관련된 내용을 훨씬 많이 강의합니다. 유튜브, 블로그 글들을 봐도 마찬가지입니다. `dplyr` 계열의 패키지들을 다루는 글이 훨씬 많습니다.
