project:
  type: website
  output-dir: _site

execute: 
  eval: true
  echo: true
  warning: false
  error: false

metadata-files: 
  - _website.yml
  - _format.yml


editor: visual
comments:
  giscus: 
    repo: rchemist0123/giscus-blog
