<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2023-02-01">
<meta name="description" content="파이프 연산자와 함께 dplyr 필수 함수들과 문법을 알아봅시다.">

<title>Rchemist - dplyr 기초 문법 이해하기</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Rchemist</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts.html">
 <span class="menu-text">Posts</span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-reader-toggle nav-link" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">dplyr 기초 문법 이해하기</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
                  <div>
        <div class="description">
          파이프 연산자와 함께 <code>dplyr</code> 필수 함수들과 문법을 알아봅시다.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">dplyr</div>
                <div class="quarto-category">R</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">February 1, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#dplyr의-동사들" id="toc-dplyr의-동사들" class="nav-link active" data-scroll-target="#dplyr의-동사들">1. dplyr의 동사들</a></li>
  <li><a href="#pipe-구조" id="toc-pipe-구조" class="nav-link" data-scroll-target="#pipe-구조">2. Pipe 구조</a></li>
  <li><a href="#filter-행-선택하기" id="toc-filter-행-선택하기" class="nav-link" data-scroll-target="#filter-행-선택하기">3. <code>filter()</code> 행 선택하기</a></li>
  <li><a href="#arrange-행-순서-정렬하기" id="toc-arrange-행-순서-정렬하기" class="nav-link" data-scroll-target="#arrange-행-순서-정렬하기">4. <code>arrange()</code>: 행 순서 정렬하기</a></li>
  <li><a href="#slice-행의-위치를-통한-행-선택" id="toc-slice-행의-위치를-통한-행-선택" class="nav-link" data-scroll-target="#slice-행의-위치를-통한-행-선택">5. <code>slice()</code>: 행의 위치를 통한 행 선택</a></li>
  <li><a href="#select-열-선택하기" id="toc-select-열-선택하기" class="nav-link" data-scroll-target="#select-열-선택하기">6. <code>select()</code>: 열 선택하기</a></li>
  <li><a href="#rename-열-이름-변경" id="toc-rename-열-이름-변경" class="nav-link" data-scroll-target="#rename-열-이름-변경">7. <code>rename()</code>: 열 이름 변경</a></li>
  <li><a href="#mutate-새로운-열-추가하기" id="toc-mutate-새로운-열-추가하기" class="nav-link" data-scroll-target="#mutate-새로운-열-추가하기">8. <code>mutate()</code>: 새로운 열 추가하기</a></li>
  <li><a href="#relocate-열의-순서-변경" id="toc-relocate-열의-순서-변경" class="nav-link" data-scroll-target="#relocate-열의-순서-변경">9. <code>relocate()</code>: 열의 순서 변경</a></li>
  <li><a href="#summarise-값들-요약" id="toc-summarise-값들-요약" class="nav-link" data-scroll-target="#summarise-값들-요약">10. <code>summarise()</code>: 값들 요약</a></li>
  </ul>
</nav>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p><code>dplyr</code> 패키지는 데이터를 다루는 패키지 중 하나로, 아래의 작업을 빠르고 쉽게 도와줄 수 있습니다.</p>
<ul>
<li><p>데이터를 다루는 흐름을 그대로 코드에 나타냄으로써, 분석 흐름을 이해하기 쉽습니다.</p></li>
<li><p>단순한 영어 동사로 이루어진 함수들을 제공하여, 작성하는 코드를 이해하기 쉽습니다.</p></li>
</ul>
<p><code>dplyr</code> 패키지에 대해 설명하기 위해 <code>starwars</code> 데이터를 사용하도록 하겠습니다. 자세한 사항은 <code>?starwars</code> 를 통해 확인할 수 있습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>starwars</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 14
   name        height  mass hair_…¹ skin_…² eye_c…³ birth…⁴ sex   gender homew…⁵
   &lt;chr&gt;        &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  
 1 Luke Skywa…    172    77 blond   fair    blue       19   male  mascu… Tatooi…
 2 C-3PO          167    75 &lt;NA&gt;    gold    yellow    112   none  mascu… Tatooi…
 3 R2-D2           96    32 &lt;NA&gt;    white,… red        33   none  mascu… Naboo  
 4 Darth Vader    202   136 none    white   yellow     41.9 male  mascu… Tatooi…
 5 Leia Organa    150    49 brown   light   brown      19   fema… femin… Aldera…
 6 Owen Lars      178   120 brown,… light   blue       52   male  mascu… Tatooi…
 7 Beru White…    165    75 brown   light   blue       47   fema… femin… Tatooi…
 8 R5-D4           97    32 &lt;NA&gt;    white,… red        NA   none  mascu… Tatooi…
 9 Biggs Dark…    183    84 black   light   brown      24   male  mascu… Tatooi…
10 Obi-Wan Ke…    182    77 auburn… fair    blue-g…    57   male  mascu… Stewjon
# … with 77 more rows, 4 more variables: species &lt;chr&gt;, films &lt;list&gt;,
#   vehicles &lt;list&gt;, starships &lt;list&gt;, and abbreviated variable names
#   ¹​hair_color, ²​skin_color, ³​eye_color, ⁴​birth_year, ⁵​homeworld</code></pre>
</div>
</div>
<p><code>starwars</code>는 <code>tibble</code> 데이터 구조를 갖습니다. 이는 <code>dplyr</code> 로 데이터를 불러올 때의 데이터 구조입니다. <code>tibble</code>은 <code>data.frame</code>과 동일한 구조이지만 다른 점이 존재합니다.</p>
<ul>
<li><p><code>tibble</code>은 달리 행의 일부분만 보여줍니다.</p></li>
<li><p><code>tibble</code>은 column의 데이터 유형(type)도 바로 알려줍니다.</p></li>
</ul>
<section id="dplyr의-동사들" class="level3">
<h3 class="anchored" data-anchor-id="dplyr의-동사들">1. dplyr의 동사들</h3>
<p>dplyr는 영어 단어 동사를 함수로 사용하여 데이터를 다루게 됩니다. 이 함수들은 크게 세 가지로 나누어 볼 수 있습니다.</p>
<ul>
<li><p>행 (Rows)</p>
<ul>
<li><p><code>filter()</code> : column을 기준으로 조건에 맞는 행들을 선택합니다.</p></li>
<li><p><code>slice()</code> : 위치를 기준으로 행들을 선택합니다.</p></li>
<li><p><code>arrange()</code> : 행의 순서를 변경합니다.</p></li>
</ul></li>
<li><p>열 (Columns)</p>
<ul>
<li><p><code>select()</code> : 특정 열을 선택합니다.</p></li>
<li><p><code>rename()</code> : 열의 이름을 변경합니다.</p></li>
<li><p><code>mutate()</code> : 새로운 열을 추가합니다.</p></li>
<li><p><code>relocate()</code> : 열의 순서를 변경합니다.</p></li>
</ul></li>
<li><p>행 요약</p>
<ul>
<li><code>summarise()</code> : 여러 행을 계산합니다.</li>
</ul></li>
</ul>
</section>
<section id="pipe-구조" class="level3">
<h3 class="anchored" data-anchor-id="pipe-구조">2. Pipe 구조</h3>
<p>모든 <code>dplyr</code>의 함수는 분석하고자 하는 데이터(<code>tibble</code>)을 첫 번째 인자로 받습니다. <code>dplyr</code>에서는 <code>f(x,y)</code> 구조 보다는 <code>x %&gt;% f(y)</code> 형태로 입력합니다. 이 때 <code>%&gt;%</code>또는<code>|&gt;</code>를 <u><strong>pipe 연산자</strong></u>라고 합니다. 파이프 연산자를 여러 번 사용하여 여러 함수를 이어서 실행할 수 있습니다.</p>
<hr>
</section>
<section id="filter-행-선택하기" class="level3">
<h3 class="anchored" data-anchor-id="filter-행-선택하기">3. <code>filter()</code> 행 선택하기</h3>
<p><code>filter()</code>는 데이터에서 일부 행들을 선택하는 함수입니다. filter() 안에는 찾고자 하는 조건이 <code>TRUE</code>인 행들만 선택이 되게 됩니다.</p>
<p>예를 들어, starwars 데이터에서 <code>skin_color</code>가 light이고 <code>eye_color</code>가 brown인 경우를 찾을 때는</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">filter</span>(skin_color<span class="sc">==</span><span class="st">'light'</span>,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                   eye_color<span class="sc">==</span><span class="st">'brown'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 14
  name         height  mass hair_…¹ skin_…² eye_c…³ birth…⁴ sex   gender homew…⁵
  &lt;chr&gt;         &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  
1 Leia Organa     150    49 brown   light   brown        19 fema… femin… Aldera…
2 Biggs Darkl…    183    84 black   light   brown        24 male  mascu… Tatooi…
3 Cordé           157    NA brown   light   brown        NA fema… femin… Naboo  
4 Dormé           165    NA brown   light   brown        NA fema… femin… Naboo  
5 Raymus Anti…    188    79 brown   light   brown        NA male  mascu… Aldera…
6 Poe Dameron      NA    NA brown   light   brown        NA male  mascu… &lt;NA&gt;   
7 Padmé Amida…    165    45 brown   light   brown        46 fema… femin… Naboo  
# … with 4 more variables: species &lt;chr&gt;, films &lt;list&gt;, vehicles &lt;list&gt;,
#   starships &lt;list&gt;, and abbreviated variable names ¹​hair_color, ²​skin_color,
#   ³​eye_color, ⁴​birth_year, ⁵​homeworld</code></pre>
</div>
</div>
<p>이는 기본 R 코드에서 다음과 같이 구현할 수 있습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>starwars[starwars<span class="sc">$</span>skin_color<span class="sc">==</span><span class="st">'light'</span> <span class="sc">&amp;</span> starwars<span class="sc">$</span>eye_color<span class="sc">==</span><span class="st">'brown'</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 14
  name         height  mass hair_…¹ skin_…² eye_c…³ birth…⁴ sex   gender homew…⁵
  &lt;chr&gt;         &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  
1 Leia Organa     150    49 brown   light   brown        19 fema… femin… Aldera…
2 Biggs Darkl…    183    84 black   light   brown        24 male  mascu… Tatooi…
3 Cordé           157    NA brown   light   brown        NA fema… femin… Naboo  
4 Dormé           165    NA brown   light   brown        NA fema… femin… Naboo  
5 Raymus Anti…    188    79 brown   light   brown        NA male  mascu… Aldera…
6 Poe Dameron      NA    NA brown   light   brown        NA male  mascu… &lt;NA&gt;   
7 Padmé Amida…    165    45 brown   light   brown        46 fema… femin… Naboo  
# … with 4 more variables: species &lt;chr&gt;, films &lt;list&gt;, vehicles &lt;list&gt;,
#   starships &lt;list&gt;, and abbreviated variable names ¹​hair_color, ²​skin_color,
#   ³​eye_color, ⁴​birth_year, ⁵​homeworld</code></pre>
</div>
</div>
</section>
<section id="arrange-행-순서-정렬하기" class="level3">
<h3 class="anchored" data-anchor-id="arrange-행-순서-정렬하기">4. <code>arrange()</code>: 행 순서 정렬하기</h3>
<p><code>arrange()</code>는 <code>filter()</code>와 동일하게 행을 다루는 함수입니다. 다만 <code>arrange()</code>는 다루는 데이터의 행을 재정렬합니다.</p>
<p>만약 두 가지 이상의 열 이름을 제공하는 경우, 첫 번째 열에서 같은 값이 나왔을 때, 추가적으로 행을 정렬하는 기준이 정해지게 됩니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">arrange</span>(height, mass)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 14
   name        height  mass hair_…¹ skin_…² eye_c…³ birth…⁴ sex   gender homew…⁵
   &lt;chr&gt;        &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  
 1 Yoda            66    17 white   green   brown       896 male  mascu… &lt;NA&gt;   
 2 Ratts Tyer…     79    15 none    grey, … unknown      NA male  mascu… Aleen …
 3 Wicket Sys…     88    20 brown   brown   brown         8 male  mascu… Endor  
 4 Dud Bolt        94    45 none    blue, … yellow       NA male  mascu… Vulpter
 5 R2-D2           96    32 &lt;NA&gt;    white,… red          33 none  mascu… Naboo  
 6 R4-P17          96    NA none    silver… red, b…      NA none  femin… &lt;NA&gt;   
 7 R5-D4           97    32 &lt;NA&gt;    white,… red          NA none  mascu… Tatooi…
 8 Sebulba        112    40 none    grey, … orange       NA male  mascu… Malast…
 9 Gasgano        122    NA none    white,… black        NA male  mascu… Troiken
10 Watto          137    NA black   blue, … yellow       NA male  mascu… Toydar…
# … with 77 more rows, 4 more variables: species &lt;chr&gt;, films &lt;list&gt;,
#   vehicles &lt;list&gt;, starships &lt;list&gt;, and abbreviated variable names
#   ¹​hair_color, ²​skin_color, ³​eye_color, ⁴​birth_year, ⁵​homeworld</code></pre>
</div>
</div>
<p>height를 기준으로 오름차순이 되었고, height가 같은 경우에는 mass가 작은 값부터 오게끔 정렬되었습니다.</p>
<p>만약 내림차순으로 데이터를 정렬하고 싶은 경우는 <code>desc()</code> 를 함께 사용하면 됩니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(height))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 14
   name        height  mass hair_…¹ skin_…² eye_c…³ birth…⁴ sex   gender homew…⁵
   &lt;chr&gt;        &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  
 1 Yarael Poof    264    NA none    white   yellow     NA   male  mascu… Quermia
 2 Tarfful        234   136 brown   brown   blue       NA   male  mascu… Kashyy…
 3 Lama Su        229    88 none    grey    black      NA   male  mascu… Kamino 
 4 Chewbacca      228   112 brown   unknown blue      200   male  mascu… Kashyy…
 5 Roos Tarpa…    224    82 none    grey    orange     NA   male  mascu… Naboo  
 6 Grievous       216   159 none    brown,… green,…    NA   male  mascu… Kalee  
 7 Taun We        213    NA none    grey    black      NA   fema… femin… Kamino 
 8 Rugor Nass     206    NA none    green   orange     NA   male  mascu… Naboo  
 9 Tion Medon     206    80 none    grey    black      NA   male  mascu… Utapau 
10 Darth Vader    202   136 none    white   yellow     41.9 male  mascu… Tatooi…
# … with 77 more rows, 4 more variables: species &lt;chr&gt;, films &lt;list&gt;,
#   vehicles &lt;list&gt;, starships &lt;list&gt;, and abbreviated variable names
#   ¹​hair_color, ²​skin_color, ³​eye_color, ⁴​birth_year, ⁵​homeworld</code></pre>
</div>
</div>
</section>
<section id="slice-행의-위치를-통한-행-선택" class="level3">
<h3 class="anchored" data-anchor-id="slice-행의-위치를-통한-행-선택">5. <code>slice()</code>: 행의 위치를 통한 행 선택</h3>
<p><code>slice()</code>는 행의 번호(index)를 통해 행들을 선택합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="dv">5</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 14
  name         height  mass hair_…¹ skin_…² eye_c…³ birth…⁴ sex   gender homew…⁵
  &lt;chr&gt;         &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  
1 Leia Organa     150    49 brown   light   brown        19 fema… femin… Aldera…
2 Owen Lars       178   120 brown,… light   blue         52 male  mascu… Tatooi…
3 Beru Whites…    165    75 brown   light   blue         47 fema… femin… Tatooi…
4 R5-D4            97    32 &lt;NA&gt;    white,… red          NA none  mascu… Tatooi…
5 Biggs Darkl…    183    84 black   light   brown        24 male  mascu… Tatooi…
6 Obi-Wan Ken…    182    77 auburn… fair    blue-g…      57 male  mascu… Stewjon
# … with 4 more variables: species &lt;chr&gt;, films &lt;list&gt;, vehicles &lt;list&gt;,
#   starships &lt;list&gt;, and abbreviated variable names ¹​hair_color, ²​skin_color,
#   ³​eye_color, ⁴​birth_year, ⁵​homeworld</code></pre>
</div>
</div>
<p><code>slice()</code>와 유사하게 사용할 수 있는 다음과 같습니다.</p>
<ul>
<li><p><code>slice_head()</code>, <code>slice_tail()</code>: 각각 데이터의 첫 ~행, 마지막 ~행을 선택할 수 있습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">slice_head</span>(<span class="at">n=</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 14
  name         height  mass hair_…¹ skin_…² eye_c…³ birth…⁴ sex   gender homew…⁵
  &lt;chr&gt;         &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  
1 Luke Skywal…    172    77 blond   fair    blue       19   male  mascu… Tatooi…
2 C-3PO           167    75 &lt;NA&gt;    gold    yellow    112   none  mascu… Tatooi…
3 R2-D2            96    32 &lt;NA&gt;    white,… red        33   none  mascu… Naboo  
4 Darth Vader     202   136 none    white   yellow     41.9 male  mascu… Tatooi…
5 Leia Organa     150    49 brown   light   brown      19   fema… femin… Aldera…
# … with 4 more variables: species &lt;chr&gt;, films &lt;list&gt;, vehicles &lt;list&gt;,
#   starships &lt;list&gt;, and abbreviated variable names ¹​hair_color, ²​skin_color,
#   ³​eye_color, ⁴​birth_year, ⁵​homeworld</code></pre>
</div>
</div></li>
<li><p><code>slice_sample()</code>: 무작위로 행을 선택합니다. <code>n</code>을 통해 행의 개수를 선택하거나, <code>prop</code> 옵션을 통해 특정 비율만큼 행을 선택할 수 있습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 14
   name        height  mass hair_…¹ skin_…² eye_c…³ birth…⁴ sex   gender homew…⁵
   &lt;chr&gt;        &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  
 1 Rey             NA    NA brown   light   hazel        NA fema… femin… &lt;NA&gt;   
 2 Sebulba        112    40 none    grey, … orange       NA male  mascu… Malast…
 3 Wedge Anti…    170    77 brown   fair    hazel        21 male  mascu… Corell…
 4 Gregar Typ…    185    85 black   dark    brown        NA male  mascu… Naboo  
 5 Taun We        213    NA none    grey    black        NA fema… femin… Kamino 
 6 Captain Ph…     NA    NA unknown unknown unknown      NA &lt;NA&gt;  &lt;NA&gt;   &lt;NA&gt;   
 7 Grievous       216   159 none    brown,… green,…      NA male  mascu… Kalee  
 8 Mas Amedda     196    NA none    blue    blue         NA male  mascu… Champa…
 9 Dormé          165    NA brown   light   brown        NA fema… femin… Naboo  
10 Shmi Skywa…    163    NA black   fair    brown        72 fema… femin… Tatooi…
# … with 4 more variables: species &lt;chr&gt;, films &lt;list&gt;, vehicles &lt;list&gt;,
#   starships &lt;list&gt;, and abbreviated variable names ¹​hair_color, ²​skin_color,
#   ³​eye_color, ⁴​birth_year, ⁵​homeworld</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">slice_sample</span>(<span class="at">prop =</span> <span class="fl">0.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 14
  name         height  mass hair_…¹ skin_…² eye_c…³ birth…⁴ sex   gender homew…⁵
  &lt;chr&gt;         &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  
1 Han Solo        180    80 brown   fair    brown      29   male  mascu… Corell…
2 Darth Vader     202   136 none    white   yellow     41.9 male  mascu… Tatooi…
3 Jango Fett      183    79 black   tan     brown      66   male  mascu… Concor…
4 Wat Tambor      193    48 none    green,… unknown    NA   male  mascu… Skako  
5 Jar Jar Bin…    196    66 none    orange  orange     52   male  mascu… Naboo  
6 Dooku           193    80 white   fair    brown     102   male  mascu… Serenno
7 Jabba Desil…    175  1358 &lt;NA&gt;    green-… orange    600   herm… mascu… Nal Hu…
8 Obi-Wan Ken…    182    77 auburn… fair    blue-g…    57   male  mascu… Stewjon
# … with 4 more variables: species &lt;chr&gt;, films &lt;list&gt;, vehicles &lt;list&gt;,
#   starships &lt;list&gt;, and abbreviated variable names ¹​hair_color, ²​skin_color,
#   ³​eye_color, ⁴​birth_year, ⁵​homeworld</code></pre>
</div>
</div>
<p><code>replace=T</code>를 통해 복원추출을 수행할 수 있습니다.</p></li>
<li><p><code>slice_min()</code>, <code>slice_max()</code>를 통해 특정 열의 가장 높거나 가장 낮은 값을 갖는 행을 선택할 수 있습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(height,<span class="at">n=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 14
  name        height  mass hair_c…¹ skin_…² eye_c…³ birth…⁴ sex   gender homew…⁵
  &lt;chr&gt;        &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  
1 Yarael Poof    264    NA none     white   yellow       NA male  mascu… Quermia
2 Tarfful        234   136 brown    brown   blue         NA male  mascu… Kashyy…
3 Lama Su        229    88 none     grey    black        NA male  mascu… Kamino 
# … with 4 more variables: species &lt;chr&gt;, films &lt;list&gt;, vehicles &lt;list&gt;,
#   starships &lt;list&gt;, and abbreviated variable names ¹​hair_color, ²​skin_color,
#   ³​eye_color, ⁴​birth_year, ⁵​homeworld</code></pre>
</div>
</div></li>
</ul>
</section>
<section id="select-열-선택하기" class="level3">
<h3 class="anchored" data-anchor-id="select-열-선택하기">6. <code>select()</code>: 열 선택하기</h3>
<p>큰 데이터를 다루게 될 경우, 많은 열이 존재하기 마련입니다. 이 중 분석하고자 하는 일부의 열만 선택할 수 있도록 도와주는 함수가 바로 <code>select()</code>입니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">select</span>(hair_color, skin_color, eye_color)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 3
   hair_color    skin_color  eye_color
   &lt;chr&gt;         &lt;chr&gt;       &lt;chr&gt;    
 1 blond         fair        blue     
 2 &lt;NA&gt;          gold        yellow   
 3 &lt;NA&gt;          white, blue red      
 4 none          white       yellow   
 5 brown         light       brown    
 6 brown, grey   light       blue     
 7 brown         light       blue     
 8 &lt;NA&gt;          white, red  red      
 9 black         light       brown    
10 auburn, white fair        blue-gray
# … with 77 more rows</code></pre>
</div>
</div>
<p>만약 열들이 붙어 있다면 <code>:</code>을 이용해 한번에 출력할 수도 있습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">select</span>(hair_color<span class="sc">:</span>eye_color)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 3
   hair_color    skin_color  eye_color
   &lt;chr&gt;         &lt;chr&gt;       &lt;chr&gt;    
 1 blond         fair        blue     
 2 &lt;NA&gt;          gold        yellow   
 3 &lt;NA&gt;          white, blue red      
 4 none          white       yellow   
 5 brown         light       brown    
 6 brown, grey   light       blue     
 7 brown         light       blue     
 8 &lt;NA&gt;          white, red  red      
 9 black         light       brown    
10 auburn, white fair        blue-gray
# … with 77 more rows</code></pre>
</div>
</div>
<p>또한 <code>select()</code> 안에서 열 이름이 갖는 규칙을 활용하여, 특정 규칙만을 갖는 열만 선택할 수 있습니다.</p>
<ul>
<li><p><code>starts_with()</code> : 특정한 값으로 시작하는 열 이름 찾기</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">'hair'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 1
   hair_color   
   &lt;chr&gt;        
 1 blond        
 2 &lt;NA&gt;         
 3 &lt;NA&gt;         
 4 none         
 5 brown        
 6 brown, grey  
 7 brown        
 8 &lt;NA&gt;         
 9 black        
10 auburn, white
# … with 77 more rows</code></pre>
</div>
</div></li>
<li><p><code>ends_with()</code> : 특정한 값으로 끝나는 열 이름 찾기</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="fu">ends_with</span>(<span class="st">'hair'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 0</code></pre>
</div>
</div></li>
<li><p><code>matches()</code> : 정규표현식을 통한 열 이름 찾기</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="fu">matches</span>(<span class="st">'^[a-z]{4}_'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 2
   hair_color    skin_color 
   &lt;chr&gt;         &lt;chr&gt;      
 1 blond         fair       
 2 &lt;NA&gt;          gold       
 3 &lt;NA&gt;          white, blue
 4 none          white      
 5 brown         light      
 6 brown, grey   light      
 7 brown         light      
 8 &lt;NA&gt;          white, red 
 9 black         light      
10 auburn, white fair       
# … with 77 more rows</code></pre>
</div>
</div></li>
<li><p><code>contains()</code> :특정한 문자가 포함된 열 이름 찾기</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">'_'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 4
   hair_color    skin_color  eye_color birth_year
   &lt;chr&gt;         &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
 1 blond         fair        blue            19  
 2 &lt;NA&gt;          gold        yellow         112  
 3 &lt;NA&gt;          white, blue red             33  
 4 none          white       yellow          41.9
 5 brown         light       brown           19  
 6 brown, grey   light       blue            52  
 7 brown         light       blue            47  
 8 &lt;NA&gt;          white, red  red             NA  
 9 black         light       brown           24  
10 auburn, white fair        blue-gray       57  
# … with 77 more rows</code></pre>
</div>
</div></li>
<li><p><code>num_range()</code> : 특정 숫자범위를 갖는 열 이름 찾기</p>
<p><code>num_range()</code> 함수를 설명하기 위해 <code>tidyr</code> 패키지에 있는 <code>billboard</code> 데이터를 사용하겠습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>billboard <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="fu">num_range</span>(<span class="st">'wk'</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 317 × 10
     wk1   wk2   wk3   wk4   wk5   wk6   wk7   wk8   wk9  wk10
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1    87    82    72    77    87    94    99    NA    NA    NA
 2    91    87    92    NA    NA    NA    NA    NA    NA    NA
 3    81    70    68    67    66    57    54    53    51    51
 4    76    76    72    69    67    65    55    59    62    61
 5    57    34    25    17    17    31    36    49    53    57
 6    51    39    34    26    26    19     2     2     3     6
 7    97    97    96    95   100    NA    NA    NA    NA    NA
 8    84    62    51    41    38    35    35    38    38    36
 9    59    53    38    28    21    18    16    14    12    10
10    76    76    74    69    68    67    61    58    57    59
# … with 307 more rows</code></pre>
</div>
</div></li>
</ul>
</section>
<section id="rename-열-이름-변경" class="level3">
<h3 class="anchored" data-anchor-id="rename-열-이름-변경">7. <code>rename()</code>: 열 이름 변경</h3>
<p><code>select()</code>문을 이용해 원하는 이름으로 열을 출력할 수도 있습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="at">home_world=</span>homeworld)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 1
   home_world
   &lt;chr&gt;     
 1 Tatooine  
 2 Tatooine  
 3 Naboo     
 4 Tatooine  
 5 Alderaan  
 6 Tatooine  
 7 Tatooine  
 8 Tatooine  
 9 Tatooine  
10 Stewjon   
# … with 77 more rows</code></pre>
</div>
</div>
<p>그러나 <code>select()</code>는 선택된 열 이외에 다른 열들은 모두 버리기 때문에, <code>rename()</code>을 이용해 열 이름을 변경해줄 수 있습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># rename(new = old)</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">rename</span>(<span class="at">home_world =</span> homeworld)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 14
   name        height  mass hair_…¹ skin_…² eye_c…³ birth…⁴ sex   gender home_…⁵
   &lt;chr&gt;        &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  
 1 Luke Skywa…    172    77 blond   fair    blue       19   male  mascu… Tatooi…
 2 C-3PO          167    75 &lt;NA&gt;    gold    yellow    112   none  mascu… Tatooi…
 3 R2-D2           96    32 &lt;NA&gt;    white,… red        33   none  mascu… Naboo  
 4 Darth Vader    202   136 none    white   yellow     41.9 male  mascu… Tatooi…
 5 Leia Organa    150    49 brown   light   brown      19   fema… femin… Aldera…
 6 Owen Lars      178   120 brown,… light   blue       52   male  mascu… Tatooi…
 7 Beru White…    165    75 brown   light   blue       47   fema… femin… Tatooi…
 8 R5-D4           97    32 &lt;NA&gt;    white,… red        NA   none  mascu… Tatooi…
 9 Biggs Dark…    183    84 black   light   brown      24   male  mascu… Tatooi…
10 Obi-Wan Ke…    182    77 auburn… fair    blue-g…    57   male  mascu… Stewjon
# … with 77 more rows, 4 more variables: species &lt;chr&gt;, films &lt;list&gt;,
#   vehicles &lt;list&gt;, starships &lt;list&gt;, and abbreviated variable names
#   ¹​hair_color, ²​skin_color, ³​eye_color, ⁴​birth_year, ⁵​home_world</code></pre>
</div>
</div>
</section>
<section id="mutate-새로운-열-추가하기" class="level3">
<h3 class="anchored" data-anchor-id="mutate-새로운-열-추가하기">8. <code>mutate()</code>: 새로운 열 추가하기</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">height_m =</span> height <span class="sc">/</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 15
   name        height  mass hair_…¹ skin_…² eye_c…³ birth…⁴ sex   gender homew…⁵
   &lt;chr&gt;        &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  
 1 Luke Skywa…    172    77 blond   fair    blue       19   male  mascu… Tatooi…
 2 C-3PO          167    75 &lt;NA&gt;    gold    yellow    112   none  mascu… Tatooi…
 3 R2-D2           96    32 &lt;NA&gt;    white,… red        33   none  mascu… Naboo  
 4 Darth Vader    202   136 none    white   yellow     41.9 male  mascu… Tatooi…
 5 Leia Organa    150    49 brown   light   brown      19   fema… femin… Aldera…
 6 Owen Lars      178   120 brown,… light   blue       52   male  mascu… Tatooi…
 7 Beru White…    165    75 brown   light   blue       47   fema… femin… Tatooi…
 8 R5-D4           97    32 &lt;NA&gt;    white,… red        NA   none  mascu… Tatooi…
 9 Biggs Dark…    183    84 black   light   brown      24   male  mascu… Tatooi…
10 Obi-Wan Ke…    182    77 auburn… fair    blue-g…    57   male  mascu… Stewjon
# … with 77 more rows, 5 more variables: species &lt;chr&gt;, films &lt;list&gt;,
#   vehicles &lt;list&gt;, starships &lt;list&gt;, height_m &lt;dbl&gt;, and abbreviated variable
#   names ¹​hair_color, ²​skin_color, ³​eye_color, ⁴​birth_year, ⁵​homeworld</code></pre>
</div>
</div>
<p><code>tibble</code> 특성 상 새롭게 만든 열이 바로 보이지 않지만, <code>select()</code>를 이용해 출력할 수 있습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">height_m =</span> height <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(height_m, height, <span class="fu">everything</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 15
   height_m height name        mass hair_…¹ skin_…² eye_c…³ birth…⁴ sex   gender
      &lt;dbl&gt;  &lt;int&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
 1     1.72    172 Luke Skyw…    77 blond   fair    blue       19   male  mascu…
 2     1.67    167 C-3PO         75 &lt;NA&gt;    gold    yellow    112   none  mascu…
 3     0.96     96 R2-D2         32 &lt;NA&gt;    white,… red        33   none  mascu…
 4     2.02    202 Darth Vad…   136 none    white   yellow     41.9 male  mascu…
 5     1.5     150 Leia Orga…    49 brown   light   brown      19   fema… femin…
 6     1.78    178 Owen Lars    120 brown,… light   blue       52   male  mascu…
 7     1.65    165 Beru Whit…    75 brown   light   blue       47   fema… femin…
 8     0.97     97 R5-D4         32 &lt;NA&gt;    white,… red        NA   none  mascu…
 9     1.83    183 Biggs Dar…    84 black   light   brown      24   male  mascu…
10     1.82    182 Obi-Wan K…    77 auburn… fair    blue-g…    57   male  mascu…
# … with 77 more rows, 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;,
#   films &lt;list&gt;, vehicles &lt;list&gt;, starships &lt;list&gt;, and abbreviated variable
#   names ¹​hair_color, ²​skin_color, ³​eye_color, ⁴​birth_year</code></pre>
</div>
</div>
<p><code>mutate()</code> 안에서 새롭게 만든 열도 접근이 가능합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">height_m =</span> height <span class="sc">/</span> <span class="dv">100</span>,</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">BMI =</span> mass <span class="sc">/</span> (height_m<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(BMI, <span class="fu">everything</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 16
     BMI name  height  mass hair_…¹ skin_…² eye_c…³ birth…⁴ sex   gender homew…⁵
   &lt;dbl&gt; &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  
 1  26.0 Luke…    172    77 blond   fair    blue       19   male  mascu… Tatooi…
 2  26.9 C-3PO    167    75 &lt;NA&gt;    gold    yellow    112   none  mascu… Tatooi…
 3  34.7 R2-D2     96    32 &lt;NA&gt;    white,… red        33   none  mascu… Naboo  
 4  33.3 Dart…    202   136 none    white   yellow     41.9 male  mascu… Tatooi…
 5  21.8 Leia…    150    49 brown   light   brown      19   fema… femin… Aldera…
 6  37.9 Owen…    178   120 brown,… light   blue       52   male  mascu… Tatooi…
 7  27.5 Beru…    165    75 brown   light   blue       47   fema… femin… Tatooi…
 8  34.0 R5-D4     97    32 &lt;NA&gt;    white,… red        NA   none  mascu… Tatooi…
 9  25.1 Bigg…    183    84 black   light   brown      24   male  mascu… Tatooi…
10  23.2 Obi-…    182    77 auburn… fair    blue-g…    57   male  mascu… Stewjon
# … with 77 more rows, 5 more variables: species &lt;chr&gt;, films &lt;list&gt;,
#   vehicles &lt;list&gt;, starships &lt;list&gt;, height_m &lt;dbl&gt;, and abbreviated variable
#   names ¹​hair_color, ²​skin_color, ³​eye_color, ⁴​birth_year, ⁵​homeworld</code></pre>
</div>
</div>
<p>만약 기존의 열은 없애고 새로운 열만 남기고 싶다면, <code>transmute()</code> 를 이용할 수 있습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">height_m =</span> height <span class="sc">/</span> <span class="dv">100</span>,</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">BMI =</span> mass <span class="sc">/</span> (height_m<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 2
   height_m   BMI
      &lt;dbl&gt; &lt;dbl&gt;
 1     1.72  26.0
 2     1.67  26.9
 3     0.96  34.7
 4     2.02  33.3
 5     1.5   21.8
 6     1.78  37.9
 7     1.65  27.5
 8     0.97  34.0
 9     1.83  25.1
10     1.82  23.2
# … with 77 more rows</code></pre>
</div>
</div>
</section>
<section id="relocate-열의-순서-변경" class="level3">
<h3 class="anchored" data-anchor-id="relocate-열의-순서-변경">9. <code>relocate()</code>: 열의 순서 변경</h3>
<p><code>relocate()</code>는 옮길 열들과, 옮길 위치를 지정해주면 됩니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># .before or .after</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">relocate</span>(sex<span class="sc">:</span>homeworld, <span class="co"># 옮길 열들</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">.before =</span> height <span class="co"># 옮길 위치</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 14
   name        sex   gender homew…¹ height  mass hair_…² skin_…³ eye_c…⁴ birth…⁵
   &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;    &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt;
 1 Luke Skywa… male  mascu… Tatooi…    172    77 blond   fair    blue       19  
 2 C-3PO       none  mascu… Tatooi…    167    75 &lt;NA&gt;    gold    yellow    112  
 3 R2-D2       none  mascu… Naboo       96    32 &lt;NA&gt;    white,… red        33  
 4 Darth Vader male  mascu… Tatooi…    202   136 none    white   yellow     41.9
 5 Leia Organa fema… femin… Aldera…    150    49 brown   light   brown      19  
 6 Owen Lars   male  mascu… Tatooi…    178   120 brown,… light   blue       52  
 7 Beru White… fema… femin… Tatooi…    165    75 brown   light   blue       47  
 8 R5-D4       none  mascu… Tatooi…     97    32 &lt;NA&gt;    white,… red        NA  
 9 Biggs Dark… male  mascu… Tatooi…    183    84 black   light   brown      24  
10 Obi-Wan Ke… male  mascu… Stewjon    182    77 auburn… fair    blue-g…    57  
# … with 77 more rows, 4 more variables: species &lt;chr&gt;, films &lt;list&gt;,
#   vehicles &lt;list&gt;, starships &lt;list&gt;, and abbreviated variable names
#   ¹​homeworld, ²​hair_color, ³​skin_color, ⁴​eye_color, ⁵​birth_year</code></pre>
</div>
</div>
</section>
<section id="summarise-값들-요약" class="level3">
<h3 class="anchored" data-anchor-id="summarise-값들-요약">10. <code>summarise()</code>: 값들 요약</h3>
<p><code>summarise()</code> 는 하나의 열을 평균, 표준편차, 중앙값 등으로 요약하기 위해 함께 사용되는 함수입니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>starwars <span class="sc">|&gt;</span> <span class="fu">summarise</span>(<span class="at">height =</span> <span class="fu">mean</span>(height, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  height
   &lt;dbl&gt;
1   174.</code></pre>
</div>
</div>
<p><code>dplyr</code>와 <code>%&gt;%</code>(또는 <code>|&gt;</code>)를 사용하여 출력했을 때, 출력된 값이 저장되지 않습니다. 즉 분석하는 데이터에는 변경사항이 없습니다. 만약 새로운 열을 추가하거나 이름을 변경할 때, 또는 계산한 값을 저장하기 위해서는 <code>&lt;-</code> 를 이용해 데이터에 저장하거나 새로운 값으로 선언해야 합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>starwars2 <span class="ot">&lt;-</span> starwars <span class="sc">%&gt;%</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(species, sex) <span class="sc">%&gt;%</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(height, mass) <span class="sc">%&gt;%</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">height =</span> <span class="fu">mean</span>(height, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mass =</span> <span class="fu">mean</span>(mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a><span class="co"># starwars2에는 group_by 후 summarise한 값만 존재</span></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>starwars2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 41 × 4
# Groups:   species [38]
   species   sex    height  mass
   &lt;chr&gt;     &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 Aleena    male      79   15  
 2 Besalisk  male     198  102  
 3 Cerean    male     198   82  
 4 Chagrian  male     196  NaN  
 5 Clawdite  female   168   55  
 6 Droid     none     131.  69.8
 7 Dug       male     112   40  
 8 Ewok      male      88   20  
 9 Geonosian male     183   80  
10 Gungan    male     209.  74  
# … with 31 more rows</code></pre>
</div>
</div>
<p>Reference</p>
<ul>
<li>https://dplyr.tidyverse.org/articles/dplyr.html</li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<pre class="markdown" data-shortcodes="false"><code>---
title: "dplyr 기초 문법 이해하기"
description:  "파이프 연산자와 함께 `dplyr` 필수 함수들과 문법을 알아봅시다."
date: '2023-02-01'
categories: [dplyr, R]
---

`dplyr` 패키지는 데이터를 다루는 패키지 중 하나로, 아래의 작업을 빠르고 쉽게 도와줄 수 있습니다.

-   데이터를 다루는 흐름을 그대로 코드에 나타냄으로써, 분석 흐름을 이해하기 쉽습니다.

-   단순한 영어 동사로 이루어진 함수들을 제공하여, 작성하는 코드를 이해하기 쉽습니다.

`dplyr` 패키지에 대해 설명하기 위해 `starwars` 데이터를 사용하도록 하겠습니다. 자세한 사항은 `?starwars` 를 통해 확인할 수 있습니다.

quarto-executable-code-5450563D

```r
library(dplyr)

starwars
```

`starwars`는 `tibble` 데이터 구조를 갖습니다. 이는 `dplyr` 로 데이터를 불러올 때의 데이터 구조입니다. `tibble`은 `data.frame`과 동일한 구조이지만 다른 점이 존재합니다.

-   `tibble`은 달리 행의 일부분만 보여줍니다.

-   `tibble`은 column의 데이터 유형(type)도 바로 알려줍니다.

### 1. dplyr의 동사들

dplyr는 영어 단어 동사를 함수로 사용하여 데이터를 다루게 됩니다. 이 함수들은 크게 세 가지로 나누어 볼 수 있습니다.

-   행 (Rows)

    -   `filter()` : column을 기준으로 조건에 맞는 행들을 선택합니다.

    -   `slice()` : 위치를 기준으로 행들을 선택합니다.

    -   `arrange()` : 행의 순서를 변경합니다.

-   열 (Columns)

    -   `select()` : 특정 열을 선택합니다.

    -   `rename()` : 열의 이름을 변경합니다.

    -   `mutate()` : 새로운 열을 추가합니다.

    -   `relocate()` : 열의 순서를 변경합니다.

-   행 요약

    -   `summarise()` : 여러 행을 계산합니다.

### 2. Pipe 구조

모든 `dplyr`의 함수는 분석하고자 하는 데이터(`tibble`)을 첫 번째 인자로 받습니다. `dplyr`에서는 `f(x,y)` 구조 보다는 `x %&gt;% f(y)` 형태로 입력합니다. 이 때 `%&gt;%`또는`|&gt;`를 [**pipe 연산자**]{.underline}라고 합니다. 파이프 연산자를 여러 번 사용하여 여러 함수를 이어서 실행할 수 있습니다.

------------------------------------------------------------------------

### 3. `filter()` 행 선택하기

`filter()`는 데이터에서 일부 행들을 선택하는 함수입니다. filter() 안에는 찾고자 하는 조건이 `TRUE`인 행들만 선택이 되게 됩니다.

예를 들어, starwars 데이터에서 `skin_color`가 light이고 `eye_color`가 brown인 경우를 찾을 때는

quarto-executable-code-5450563D

```r
starwars |&gt; filter(skin_color=='light',
                   eye_color=='brown')
```

이는 기본 R 코드에서 다음과 같이 구현할 수 있습니다.

quarto-executable-code-5450563D

```r
starwars[starwars$skin_color=='light' &amp; starwars$eye_color=='brown',]
```

### 4. `arrange()`: 행 순서 정렬하기

`arrange()`는 `filter()`와 동일하게 행을 다루는 함수입니다. 다만 `arrange()`는 다루는 데이터의 행을 재정렬합니다.

만약 두 가지 이상의 열 이름을 제공하는 경우, 첫 번째 열에서 같은 값이 나왔을 때, 추가적으로 행을 정렬하는 기준이 정해지게 됩니다.

quarto-executable-code-5450563D

```r
starwars |&gt; arrange(height, mass)
```

height를 기준으로 오름차순이 되었고, height가 같은 경우에는 mass가 작은 값부터 오게끔 정렬되었습니다.

만약 내림차순으로 데이터를 정렬하고 싶은 경우는 `desc()` 를 함께 사용하면 됩니다.

quarto-executable-code-5450563D

```r
starwars |&gt; arrange(desc(height))
```

### 5. `slice()`: 행의 위치를 통한 행 선택

`slice()`는 행의 번호(index)를 통해 행들을 선택합니다.

quarto-executable-code-5450563D

```r
starwars |&gt; slice(5:10)
```

`slice()`와 유사하게 사용할 수 있는 다음과 같습니다.

-   `slice_head()`, `slice_tail()`: 각각 데이터의 첫 \~행, 마지막 \~행을 선택할 수 있습니다.

    ```{r}
    starwars |&gt; slice_head(n=5)
    ```

-   `slice_sample()`: 무작위로 행을 선택합니다. `n`을 통해 행의 개수를 선택하거나, `prop` 옵션을 통해 특정 비율만큼 행을 선택할 수 있습니다.

    ```{r}
    starwars |&gt; slice_sample(n=10)
    starwars |&gt; slice_sample(prop = 0.1)
    ```

    `replace=T`를 통해 복원추출을 수행할 수 있습니다.

-   `slice_min()`, `slice_max()`를 통해 특정 열의 가장 높거나 가장 낮은 값을 갖는 행을 선택할 수 있습니다.

    ```{r}
    starwars |&gt; 
      slice_max(height,n=3)
    ```

### 6. `select()`: 열 선택하기

큰 데이터를 다루게 될 경우, 많은 열이 존재하기 마련입니다. 이 중 분석하고자 하는 일부의 열만 선택할 수 있도록 도와주는 함수가 바로 `select()`입니다.

quarto-executable-code-5450563D

```r
starwars |&gt; select(hair_color, skin_color, eye_color)
```

만약 열들이 붙어 있다면 `:`을 이용해 한번에 출력할 수도 있습니다.

quarto-executable-code-5450563D

```r
starwars |&gt; select(hair_color:eye_color)
```

또한 `select()` 안에서 열 이름이 갖는 규칙을 활용하여, 특정 규칙만을 갖는 열만 선택할 수 있습니다.

-   `starts_with()` : 특정한 값으로 시작하는 열 이름 찾기

    ```{r}
    starwars |&gt; select(starts_with('hair'))
    ```

-   `ends_with()` : 특정한 값으로 끝나는 열 이름 찾기

    ```{r}
    starwars |&gt; select(ends_with('hair'))
    ```

-   `matches()` : 정규표현식을 통한 열 이름 찾기

    ```{r}
    starwars |&gt; select(matches('^[a-z]{4}_'))
    ```

-   `contains()` :특정한 문자가 포함된 열 이름 찾기

    ```{r}
    starwars |&gt; select(contains('_'))
    ```

-   `num_range()` : 특정 숫자범위를 갖는 열 이름 찾기

    `num_range()` 함수를 설명하기 위해 `tidyr` 패키지에 있는 `billboard` 데이터를 사용하겠습니다.

    ```{r}
    library(tidyr)
    billboard |&gt; select(num_range('wk',1:10))
    ```

### 7. `rename()`: 열 이름 변경

`select()`문을 이용해 원하는 이름으로 열을 출력할 수도 있습니다.

quarto-executable-code-5450563D

```r
starwars |&gt; select(home_world=homeworld)
```

그러나 `select()`는 선택된 열 이외에 다른 열들은 모두 버리기 때문에, `rename()`을 이용해 열 이름을 변경해줄 수 있습니다.

quarto-executable-code-5450563D

```r
# rename(new = old)
starwars |&gt; rename(home_world = homeworld)
```

### 8. `mutate()`: 새로운 열 추가하기

quarto-executable-code-5450563D

```r
starwars |&gt; mutate(height_m = height / 100)
```

`tibble` 특성 상 새롭게 만든 열이 바로 보이지 않지만, `select()`를 이용해 출력할 수 있습니다.

quarto-executable-code-5450563D

```r
starwars |&gt;
  mutate(height_m = height / 100) %&gt;%
  select(height_m, height, everything())
```

`mutate()` 안에서 새롭게 만든 열도 접근이 가능합니다.

quarto-executable-code-5450563D

```r
starwars |&gt; 
  mutate(
    height_m = height / 100,
    BMI = mass / (height_m^2)
  ) %&gt;%
  select(BMI, everything())
```

만약 기존의 열은 없애고 새로운 열만 남기고 싶다면, `transmute()` 를 이용할 수 있습니다.

quarto-executable-code-5450563D

```r
starwars |&gt;
  transmute(
    height_m = height / 100,
    BMI = mass / (height_m^2)
  )
```

### 9. `relocate()`: 열의 순서 변경

`relocate()`는 옮길 열들과, 옮길 위치를 지정해주면 됩니다.

quarto-executable-code-5450563D

```r
# .before or .after
starwars |&gt; relocate(sex:homeworld, # 옮길 열들
                    .before = height # 옮길 위치
                    )
```

### 10. `summarise()`: 값들 요약

`summarise()` 는 하나의 열을 평균, 표준편차, 중앙값 등으로 요약하기 위해 함께 사용되는 함수입니다.

quarto-executable-code-5450563D

```r
starwars |&gt; summarise(height = mean(height, na.rm = TRUE))
```

`dplyr`와 `%&gt;%`(또는 `|&gt;`)를 사용하여 출력했을 때, 출력된 값이 저장되지 않습니다. 즉 분석하는 데이터에는 변경사항이 없습니다. 만약 새로운 열을 추가하거나 이름을 변경할 때, 또는 계산한 값을 저장하기 위해서는 `&lt;-` 를 이용해 데이터에 저장하거나 새로운 값으로 선언해야 합니다.

quarto-executable-code-5450563D

```r
starwars2 &lt;- starwars %&gt;%
  group_by(species, sex) %&gt;%
  select(height, mass) %&gt;%
  summarise(
    height = mean(height, na.rm = TRUE),
    mass = mean(mass, na.rm = TRUE)
  )

# starwars2에는 group_by 후 summarise한 값만 존재
starwars2
```

Reference

-   https://dplyr.tidyverse.org/articles/dplyr.html</code></pre>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left"><a href="https://https://rchemist.quarto.pub/rchemistblog/">Rchemist</a> © 2022 by <a href="https://https://rchemist.quarto.pub/rchemistblog/about.html">YH Jang</a></div>   
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:danjang0123@gmail.com">
      <i class="bi bi-envelope" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/danjang0123/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>